package(default_visibility = ["//visibility:private"])

load(
    "@build_bazel_rules_apple//apple:swift.bzl", 
    "swift_library"
)

swift_library(
    name = "multiplier",
    srcs = [
        "multiplier.swift",
    ]
)

